
<!-- 検索フォーム -->
<form action='/post/search' method='post'>
    <h2>message検索</h2>
    <!-- <fieldset> -->
      <!-- id検索 -->
        <div class='control-group'>
            <label for='id' class='control-label'>Id&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
            <input type='text' id='id' name='id' />
        </div>
        <!-- message検索 -->
        <div class='control-group'>
            <label for='message' class='control-label'>message</label>
            <input type='text' id='message' name='message' />
        </div>

        <p></p>

        <div class='control-group'>
            <input type='submit' value='Search' class='btn btn-primary' />
        </div>

        <p></p>

        <div class='control-group'>
            <a href="/post/new" class='btn btn-success'>メッセージ新規登録</a>
        </div>

    <!-- </fieldset> -->
</form>

<h1>message一覧</h1>
<?php
if ($posts->count() >= 0) {
    ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>id</th>
            <th>message</th>
            <th>line送信</th>
            <th>削除</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="3">メッセージの数: <?php echo $posts->count(); ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php foreach ($posts as $post) { ?>
            <tr>
                <td><?php echo $post->id; ?></td>
                <td><?php echo $post->message; ?></td>
                <td>
                  <form action="/post/send" method="post">
                        <input type="hidden" name="id" value="<?php echo $post->id; ?>" >
                        <input type="submit" value="lineに送信">
                  </form>
                </td>
                <td>
                  <form action="/post/delete/<?php echo $post->id; ?>" method="post">
                        <input type="submit" value="削除">
                  </form>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php
}
?>

<!-- ログアウト -->
<form action="/session/end" method="post">
      <input type="submit" value="ログアウト">
</form>
