<h1>検索結果</h1>
<?php
if ($posts->count() >= 0) {
    ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>#</th>
            <th>message</th>
            <th>line送信</th>
            <th>削除</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="3">Posts quantity: <?php echo $posts->count(); ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php foreach ($posts as $post) { ?>
            <tr>
                <td><?php echo $post->id; ?></td>
                <td><?php echo $post->message; ?></td>
                <td>
                  <form action="/post/send" method="post">
                        <input type="hidden" name="id" value="<?php echo $post->id; ?>" >
                        <input type="submit" value="lineに送信">
                  </form>
                </td>
                <td>
                  <form action="/post/delete/<?php echo $post->id; ?>" method="post">
                        <input type="submit" value="削除">
                  </form>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php
}
?>

<div class='control-group'>
    <a href="/post" class='btn btn-info'>投稿一覧</a>
</div>
