<h2>ユーザー登録</h2>

<form action="register" method="post">
  <p>
     フルネーム：<input type="text" name="name">
  </p>
  <p>
     ユーザー名：<input type="text" name="username">
  </p>
  <p>
     メールアドレス：<input type="text" name="email">
  </p>
  <p>
     パスワード：<input type="text" name="password">
  </p>
  <p>
     パスワード確認：<input type="text" name="repeatPassword">
  </p>
  <p>
     <input type="submit" value="登録">
  </p>
</form>
