<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Phalcon Tutorial</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
</head>
<body>
<div class="container">
    <!-- <p><?php echo var_dump($_SESSION); ?></p> -->
    <p><?php echo var_dump($this->session->get('auth')); ?></p>
    <p><?php echo $this->getContent(); ?></p>
</div>
</body>
</html>
